### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by uk9251** [SAP-samples/data-warehouse-cloud-connectors#14]
I have been able to successfully connect using the blank query method but get an error when trying to use the custom connector, this occurs when you select sign in.

Error 
Invalid URI: The format of the URI could not be determined

I have setup the connections file as suggested and should work as same details used for blank query.

```
[{
    "product":"DWC",
    "host": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.eu99.hcs.cloud.sap",

    "client_id": "xx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxx|client!xxxxx",
    "client_secret": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "auth_token_url": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.authentication.eu99.hana.ondemand.com/oauth/token",
    "auth_authorize_url": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.authentication.eu99.hana.ondemand.com/oauth/authorize"
}]
```

**Comment by OlafFischer** [comment]
Could you please try with the latest version? I fixed an issue on the catalog connection with a similar error message.
Best regards, Olaf

**Comment by uk9251** [comment]
Thanks now working

**Comment by OlafFischer** [comment]
Thanks for the feedback, Olaf
