### ISSUE TITLE
Power BI does not detect custom add-on

### ISSUE THREAD

**Issue by PV4SAP** [SAP-samples/data-warehouse-cloud-connectors#16]
**Power BI does not detect custom add-on**
Followed the steps of changing XML creating and renaming the zip content to .Mez file.
 
And copy paste. as detailed below. However Power BI did not pick any add-on?
![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/67643971/804fe128-ba16-40ae-9799-4c950cd82087)

**Comment by OlafFischer** [comment]
One check: The connector is not signed and hence requires to lower the security level. Have you checked this?

**Comment by PV4SAP** [comment]
Problem solved. I was putting zipped content in PowerBI program file folder. Once I moved activity to My Documents folder , it worked.ThxSent from my iPhoneOn 29 Nov 2023, at 17:47, OlafFischer ***@***.***> wrote:﻿
One check: The connector is not signed and hence requires to lower the security level. Have you checked this?

**Comment by OlafFischer** [comment]
Glad to hear that you could resolve the issue. Closing this thread.
