### ISSUE TITLE
Question about connector usage for productive scenarios

### ISSUE THREAD

**Issue by reg-giuliafelappi** [SAP-samples/data-warehouse-cloud-connectors#18]
Hello, 

I found this project from the following SAP blog post: https://blogs.sap.com/2022/10/14/sap-data-warehouse-cloud-odata-connector-for-powerbi/ 

I understood this is still in beta release since it's not an SAP standard delivery, and it's not recommended for productive usage. 
Since it does exactly what I would need for a production scenario, I'd like to understand if this connector will ever become an SAP product for production use, and if there's any product roadmap in this regard. 

Thank you!

**Comment by OlafFischer** [comment]
Hi Reg-guiliafelappi,
as of now you can use the connector based on the described open-source license - as any other open-source product. If you like to use the connector in a productive manner, I would recommend two changes:
 - The current implementation sets the "beta"-flag to true. Adjust the delivered source code to set the beta-flag to false. As a result it will not show up in the connection name any more. 
 _How to find the right place:_ Open the dwc.m file and search for "beta" and you find the right context.
 - Sign the custom connector (to be more precide the *.mez file) after you added the connection details. A signed custom connector can be used with the standard security settings of PowerBi -> no lowering is required any more. See here for more details: https://learn.microsoft.com/en-us/power-query/handling-connector-signing
