### ISSUE TITLE
Usage of connector in Excel 365

### ISSUE THREAD

**Issue by irvrodin** [SAP-samples/data-warehouse-cloud-connectors#21]
Not sure if this is a question or a feature request:
Could this connector be used (or easily enhanced) to be used in Excel 365 instead of Power BI?
Since Power Query is already natively integrated in Excel 365 it seems to me like these tools share the same backbone. The same backbone which is used in this datasphere connector.
The large userbase of excel business users that are in need of an easy-to-use odata based access method to datasphere would exponentially increase the usage of this connector.

**Comment by OlafFischer** [comment]
Hi @irvrodin ,
The implementation of the custom connector relies on MS PowerBI extension points respective APIs. The documentation provided by Microsoft only refers to MS PowerBI. Hence I assume that Excel is not and can't be supported as of now.
If you find documentation related to Excel, please share the links with me.
Best regards, Olaf Fischer
