### ISSUE TITLE
Adding Views directly via Advanced Query Editor - Expensive Result Sets

### ISSUE THREAD

**Issue by OlafFischer** [SAP-samples/data-warehouse-cloud-connectors#22]
Adding a datasource via the Wizzard approach will always show the data preview. This data preview request is a full request (all columns, no filter) - just a Top 1000 is added. There are situations, where this request times out or where the result set is too large.

In this situation, you could add the data source directly in the Advanced Query Editor of PowerBI: Find below a sample where we reduced the Top condition to 100 (good for relational sources, typically not that effective on analytical sources) and selected two specific columns (in the example the columns "HOST" and "VALUE"):

```
﻿let
     Source = SapDataWarehouseCloudConnector.Contents(
         "<tenant name>",
         "relational", 
         "<Space Name>",
         "<View Name>",
         "<Parameters> or null"),

     M_HOST_INFORMATION_S_table =
        Source{[Name="M_HOST_INFORMATION_S",Signature="table"]}[Data],

     #"TOP" = Table.FirstN(M_HOST_INFORMATION_S_table,100),

     #"COLUMNS" = Table.SelectColumns(#"TOP",{"HOST", "VALUE"})
in
     #"COLUMNS"
```

This snipped has been created using the following steps:
- Use the datasource via wizzard (dialog) and insert a simple view
- Use the standard options of PowerBI to apply a TopN conditions and to select some columns 
- Open the advanced editor  - the script that represents your view and conditions is display
- Take this script as a template and use it to insert datasphere views.

Note that PowerBI offers additional relevant options like setting filters on columns.

**Comment by sknoepfler** [comment]
@OlafFischer : I followed your exact steps (Top 10 and 2 columns) with a problematic analytic model and still got the following error:

DataSource.Error: Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 3 and 4, Error: The remote server returned an error: (500) Internal Server Error. (Unable to process query: Error: Debug [IOLayer]: (#99999) e4e2117f-9e7a-4714-770b-9b0a52d2534d
Error [Server]: (#42014) Caught exception : exception 70000004: cannot allocate enough memory: SQL Error

)
OData Version: 4, Error: The remote server returned an error: (500) Internal Server Error. (Unable to process query: Error: Debug [IOLayer]: (#99999) 251596f8-4744-4598-6903-6f0550f464f0
Error [Server]: (#42014) Caught exception : exception 70000004: cannot allocate enough memory: Allocation failed; Reason: configured statement memory limit from global configuration reached (SAP Note 3191224)
)
OData Version: 3, Error: The remote server returned an error: (500) Internal Server Error. (Unable to process query: Error: Debug [IOLayer]: (#99999) 2752614e-b8b3-4375-68d3-5311aaf54a64
Error [Server]: (#42014) Caught exception : exception 70000004: cannot allocate enough memory: SQL Error

Is there any specific setting in PowerBI that I am missing? 

Thanks in advance
Sven

**Comment by OlafFischer** [comment]
Hi Sven, 
it seems that even the limited result-set consumes more memory than available for your user.
Best regards, Olaf
