### ISSUE TITLE
404 Connection Error

### ISSUE THREAD

**Issue by EmmJayJay** [SAP-samples/data-warehouse-cloud-connectors#23]
Hi there.  We have successfully used this connector in the past, but are now having some issues.  From multiple PC clients, we receive the 404 error shown in Power BI.  Has anyone else experienced this?  We are confident our connections.json file is correct, as it has been working previously and we have checked client/secret config etc.  Many thanks.

![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/153182174/c164f5a9-7001-477a-a0ba-eae8bec4718b)

**Comment by EmmJayJay** [comment]
An update.  The "Data" connection is now working OK for us.  However, the "Catalog" connection is still producing a 404 error.  Power BI trace indicates it is at the point of calling the catalog $metadata.  On another thread somewhere, there is a post saying that there is a known issue with 404 error when calling $metadata on Datasphere 2024.11, and that it should be fixed in the next release.  I will update when we have tested again on the next release.  Thanks :)

**Comment by gustavokath** [comment]
Hi @EmmJayJay,

Thanks for raising the questions and also pointing the answer. 

I've shared this in a Blog post comments that we have an issue with $metadata request for catalog on SAP Datasphere 2024.11 and the fix will be available on the next release.

Let me know if I could help with anything else.
