### ISSUE TITLE
Power BI over SAP datasphere via Odata

### ISSUE THREAD

**Issue by shlomiweiss** [SAP-samples/data-warehouse-cloud-connectors#24]
Hi all

we are ttying to connect Power BI to SAP Datasphere via oData connector according to the following post
https://community.sap.com/t5/technology-blogs-by-sap/sap-datasphere-odata-connector-for-powerbi/bc-p/13762050#M173845

We do get the connectors 
![image](https://github.com/user-attachments/assets/097c8159-b33b-4577-8a72-52a889529d3d)

But on each of them we get the same error:
![image](https://github.com/user-attachments/assets/5edb45fd-fddb-48d8-87af-6342477fb01d)

What ae we missing?

Thanks

Shlomi

**Comment by gustavokath** [comment]
Hi @shlomiweiss,

I still lack a bit of information to identify if the connection closing was on the client or server side. Do you have some details on the error?

Also I've found some Microsoft blogs related to this error message, could you please check them:
* [The underlying connection was closed: An unexpected error occurred](https://community.fabric.microsoft.com/t5/Power-Query/The-underlying-connection-was-closed-An-unexpected-error/td-p/3032659)
* [Getting The underlying connection was closed](https://community.fabric.microsoft.com/t5/Service/Getting-The-underlying-connection-was-closed/m-p/1216847)

Feel free to open a SAP Support Ticket if you would like further assistance or would like to share details from your SAP Datasphere tenant

Thanks
Gustavo

**Comment by shlomiweiss** [comment]
Thanks

It was my mistake. I didn't run the right host

Thanks
