### ISSUE TITLE
Is there a plan to address direct queries?

### ISSUE THREAD

**Issue by KeiichiHiranoND** [SAP-samples/data-warehouse-cloud-connectors#25]
Will this connector be able to support direct queries?

I ask because I do not want to use direct queries with ODBC as I want to ensure row level security with user authentication in SAP DSP.

Best regards.

**Comment by gustavokath** [comment]
Hi @KeiichiHiranoND,

This feature request is already being discussed and under ideation phase. It has been as well request on [SAP Influence Portal](https://influence.sap.com/sap/ino/#/idea/319225) you can give a vote in there as well.

Thanks

**Comment by KeiichiHiranoND** [comment]
Hi @gustavokath ,

Thanks for the info.
I'll vote for the request right away.

Thanks

**Comment by OlafFischer** [comment]
Closing the issue
