### ISSUE TITLE
pBI does not consume business descriptions of Datasphere data products or the columns within those products

### ISSUE THREAD

**Issue by ChristophePosson** [SAP-samples/data-warehouse-cloud-connectors#27]
Hi,

I have successfully established connection to the custom connectors and to Datasphere.

I created a very simple test data product consisting of a relational dimension view that has a technical name and a business description. 3 simple fields included, also with technical name and business description:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/c51731c2-a659-4288-ab9d-f2815fbf5ff0">

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/d3e03c1b-65cc-45e4-a708-fd39b278d095">

None of the connections types I have explored immediately interpret that metadata correctly. I only get the technical names of both the view and the fields inside the view.
<img width="166" alt="image" src="https://github.com/user-attachments/assets/89cf5d6c-df93-44e1-90a0-9ac7f4380dd2">

While that is the whole selling point of SAP, Datasphere keeps the business context. But once imported in pBI that context goes lost :-)

Does anyone have similar issues and more importantly, is there a solution for this?

Thanks upfront for any help in this regard,
Christophe

PS: in the generated oData request on Datasphere side you do see the descriptions

<img width="607" alt="image" src="https://github.com/user-attachments/assets/a1ede4da-9321-487a-840f-eca7bea7d233">

**Comment by gustavokath** [comment]
Hi @ChristophePosson, 

To give some public commenting on what we discussed via email. 

I’ve investigated the Custom Connector implementation and even including more options as part of the OData.Feed on PowerBI to explicitly read metadata it does not handle the fields neither allows us to manual select the annotations included.
For your reference those annotation are: IncludeAnnotations and IncludeMetadataAnnotations as described in ([https://learn.microsoft.com/en-us/powerquery-m/odata-feed](https://learn.microsoft.com/en-us/powerquery-m/odata-feed) 

Currently there will be no specific actions on this, but we are in talks we with Microsoft for better seamless integration for PowerBI.
