### ISSUE TITLE
Host Format Change - Error message "https" not found / URL not found

### ISSUE THREAD

**Issue by OlafFischer** [SAP-samples/data-warehouse-cloud-connectors#8]
With version 1.40 - update from CW04 2023 - the format of the connections.json has been adjusted.

The property **host** now expects the host-name and not the tenant URL anymore.
Example: Instead of https://< my-tenant > you only need to provide < my-tenant >.

When you continue using the URL, you will receive the error message similar to "https" oder URL/Endpoint not found.

**Comment by OlafFischer** [comment]
Resolution: Remove the prefix https:// from your host property in the connections file.

**Comment by AnishArjun05** [comment]
Hi Olaf, sorry for the delayed response.

We did the changes that you suggested to us and it is working fine now. Thank you for taking time to resolve this issue for us.
